services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - backend
    depends_on:
      - mongodb

volumes:
  mongo-data:

networks:
  backend:
