name: Node.js CI

on:
  push:
    branches: ["main"]
    paths:
      - "driven_software_engineering/**"
  pull_request:
    branches: ["main"]
    paths:
      - "driven_software_engineering/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: driven_software_engineering # 👈 muda o diretório

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx jest
